"""Template: add a new platform by subclassing CTFPlatformClient."""
from __future__ import annotations

from typing import Any

from ctf_platforms import CTFPlatformClient, Credentials, PlatformConfig, register_platform


@register_platform("my-alias")
class MyPlatform(CTFPlatformClient):
    platform = "myplatform"
    display_name = "My CTF Platform"

    def __init__(self, config: PlatformConfig):
        super().__init__(config)
        # self.session = requests.Session(); self.base_url = config.base_url.rstrip("/")

    def probe(self) -> dict[str, Any]: ...
    def login(self, credentials: Credentials) -> dict[str, Any]:
        # if credentials.token: use token auth; else credentials.require_password()
        ...
    def load_session(self, path: str | None = None) -> dict[str, Any]: ...
    def save_session(self, path: str | None = None) -> dict[str, Any]: ...
    def current_user(self) -> dict[str, Any]: ...
    def list_contests(self, page: int = 1, page_size: int = 50, search: str | None = None) -> Any: ...
    def get_contest(self, contest_id: str | int) -> Any: ...
    def join_contest(self, contest_id: str | int, team_id: str | int | None = None, invite_code: str | None = None) -> Any: ...
    def list_challenges(self, contest_id: str | int | None = None, page: int = 1, page_size: int = 50, search: str | None = None) -> Any: ...
    def get_challenge(self, challenge_id: str | int, contest_id: str | int | None = None) -> Any: ...
    def download_attachment(self, challenge_id: str | int, outdir: str, contest_id: str | int | None = None) -> list[Any]: ...
    def submit_flag(self, challenge_id: str | int, flag: str, contest_id: str | int | None = None) -> Any: ...
    def scoreboard(self, contest_id: str | int | None = None) -> Any: ...
    def raw_client(self) -> Any: ...
